version: '3'

services:
  web:
    build: .
    image: facundopadilla/n5now:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DSN: "postgresql://postgres:n5now@db:5432/n5now"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: n5now
      POSTGRES_DB: n5now
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: