"""new tables

Revision ID: 739277c61d3d
Revises: 3d8728f2e466
Create Date: 2024-07-08 17:34:00.322182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '739277c61d3d'
down_revision: Union[str, None] = '3d8728f2e466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_violations',
    sa.Column('license_plate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('police_officer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['police_officer_id'], ['police_officers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_violations_comment'), 'traffic_violations', ['comment'], unique=True)
    op.create_index(op.f('ix_traffic_violations_license_plate'), 'traffic_violations', ['license_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_violations_license_plate'), table_name='traffic_violations')
    op.drop_index(op.f('ix_traffic_violations_comment'), table_name='traffic_violations')
    op.drop_table('traffic_violations')
    # ### end Alembic commands ###
