"""fix columns

Revision ID: b0f467cc2da8
Revises: 8c1745843726
Create Date: 2024-07-08 17:52:59.569459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0f467cc2da8'
down_revision: Union[str, None] = '8c1745843726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_traffic_violations_license_plate', table_name='traffic_violations')
    op.create_index(op.f('ix_traffic_violations_license_plate'), 'traffic_violations', ['license_plate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_violations_license_plate'), table_name='traffic_violations')
    op.create_index('ix_traffic_violations_license_plate', 'traffic_violations', ['license_plate'], unique=True)
    # ### end Alembic commands ###
