from typing import Optional

from pydantic import Field

from src.settings.base_settings import BaseProjectSettings


class _JWTSettings(BaseProjectSettings):
    JWT_PRIVATE_KEY: str = Field(
        None,
        description=(
            "Private key to create signatures, if the field is empty, "
            "the private key is generated by the project only in a test "
            "environment"
        ),
    )


JWTSettings = _JWTSettings()
